name: nightly update
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI_COMMIT_MESSAGE: daily update
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: install puppeteer
      run: npm ci
    - name: nightly update
      run: make nightly
    - name: Check diff
      id: diff
      run: |
        git add -N .
        git diff --name-only --exit-code
      continue-on-error: true
    - name: Commit and push to GitHub if needed
      if: steps.diff.outcome == 'failure'
      run: |
        git config --global user.name github-actions[bot]
        git config --global user.email "${{ secrets.MY_SECRET_EMAIL}}"
        git add .
        git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push
